### ISSUE TITLE
Util.is. failing in comparisons

### ISSUE THREAD

**Issue by ajbloureiro** [findhit/util#34]
there's a failing comparison in the Socialite middleware starting at line 240

validSession: function ( session ) 
uses Util.is.<type> which in the first comparison Util.is.Object(session) and the last Util.is.String(session.socialite.redirectUrl) fails when it shouldn't

had to rewrite the comparison to the following which finally worked

session instanceof Object && typeof session === 'object' &&
session.socialite instanceof Object && typeof session.socialite === 'object' &&
session.socialite.accounts instanceof Object && typeof session.socialite.accounts === 'object' &&
typeof session.socialite.redirectURL === 'string';

**Comment by cusspvz** [comment]
Could you provide which method is failing?

**Comment by ajbloureiro** [comment]
I've said it already ;)

**Comment by cusspvz** [comment]
Note that `foo instanceof Object` covers all variable types that inherits from `Object` prototype (which is almost all of them)

**Comment by cusspvz** [comment]
Could you please provide a test case?
